-- Initialise eveything from here
require("globals")
vim.cmd("source ~/.config/nvim/vimscript/keys.vim")
vim.cmd("luafile ~/.config/nvim/base-settings.lua")
vim.cmd("luafile ~/.config/nvim/lua/plugins/dashboard.lua")
require("install-plugins")
require("colorscheme")
require("settings")
require("utils")
require("autocommands")
require("keymappings")
require("lsp")
require("plugins")
require("debug")

