require("install-plugins")
require("globals")
require("utils")
vim.cmd("luafile ~/.config/nvim/base-settings.lua")
-- require("autocommands")
require("settings")
require("keymappings")
require("colorscheme")
-- require("galaxyline")
-- require("comment")
require("compe")
-- require("barbar")
-- require("dashboard")
require("telescope")
-- require("gitsigns")
-- require("nvimtree")
-- require("treesitter")
-- require("autopairs")
-- require("vim-rooter")

-- Which Key (Hope to replace with Lua plugin someday)
vim.cmd("source ~/.config/nvim/vimscript/whichkey/init.vim")