
     alpha-nvim
     catppuccin
     dressing.nvim
     flit.nvim
     indent-blankline.nvim
     leap.nvim
     lualine.nvim
     mini.ai
     mini.bufremove
     mini.comment
     mini.indentscope
     mini.pairs
     mini.surround
     neo-tree.nvim
     neoconf.nvim
     noice.nvim
     nui.nvim
     null-ls.nvim
     nvim-bufferline.lua
     nvim-navic
     nvim-notify
     nvim-remote-containers
     nvim-spectre
     nvim-ts-context-commentstring
     persistence.nvim
     tokyonight.nvim
     trouble.nvim
     vim-illuminate
     vim-repeat
     vim-startuptime
