return {
    -- "nvim-tree/nvim-tree.lua",
    -- lazy = false,
    -- config = function()
    --     local tree = require("nvim-tree")
    --     tree.setup({
    --         hijack_cursor = true, -- keeps the cursor on the first letter of filename while navigating.
    --         disable_netrw = true,
    --         hijack_netrw = true,
    --         hijack_unnamed_buffer_when_opening = false,
    --         hijack_directories = {
    --             enable = true,
    --             auto_open = false,
    --         },
    --         actions = {
    --             open_file = {
    --                 resize_window = true, -- resizes the tree when opening a file.
    --             },
    --         },
    --         filters = {
    --             dotfiles = true, -- do not show dotfiles, toggle with H.
    --         },
    --         view = {
    --             side = "right",
    --             width = 36,
    --         },

    --         renderer = {
    --             highlight_git = true,
    --             root_folder_label = function(path)
    --                 local project = vim.fn.fnamemodify(path, ":t")
    --                 return string.upper(project)
    --             end,
    --             indent_markers = {
    --                 enable = true,
    --             },
    --             icons = {
    --                 show = false,
    --                 glyphs = {
    --                     default = "󰦨",
    --                     symlink = "󰦨",
    --                     bookmark = "󰦨",
    --                     git = false,
    --                     folder = {
    --                         -- default = "",
    --                         symlink = "",
    --                         arrow_closed = "", -- arrow when folder is closed
    --                         arrow_open = "", -- arrow when folder is open
    --                     },
    --                 },
    --             },
    --             special_files = { "README.md" },
    --         },
    --     })
    --     vim.g.loaded_netrw = 1
    --     vim.g.loaded_netrwPlugin = 1
    -- end,
}
