#!/usr/bin/env sh

if dot::os::mac; then
    # Install the nightly build of neovim
    # https://www.reddit.com/r/SolusProject/comments/iguvn6/how_can_i_install_neovim_nightly/ghs0zjw/?context=3
    formula tap jason0x43/homebrew-neovim-nightly
    formula nightly-neovim
fi
